# create_package_pro.R
# Creates a professional-grade R package skeleton

args <- commandArgs(trailingOnly = TRUE)

if (length(args) == 0) {
  stop("Please provide a package name. Usage: Rscript create_package_pro.R 'MyProPackage'")
}

pkg_name <- args[1]
pkg_path <- file.path(getwd(), pkg_name)

if (dir.exists(pkg_path)) {
  stop(paste("Directory already exists:", pkg_path))
}

cat(paste0("🚀 Building Professional R Package Studio: ", pkg_name, "...\n"))

# 1. Base Structure
dir.create(pkg_path)
dir.dirs <- c("R", "man", "tests/testthat", "vignettes", "data-raw", ".github/workflows")
lapply(file.path(pkg_path, dir.dirs), dir.create, recursive = TRUE)

# 2. Advanced DESCRIPTION
desc <- c(
  paste0("Package: ", pkg_name),
  "Type: Package",
  "Title: Professional Package Built with Antigravity",
  "Version: 0.1.0",
  "Author: Your Name <email@example.com>",
  "Maintainer: Your Name <email@example.com>",
  "Description: A comprehensive description of what this pro package does.",
  "License: MIT + file LICENSE",
  "Encoding: UTF-8",
  "LazyData: true",
  "RoxygenNote: 7.3.2",
  "Imports: ",
  "Suggests: ",
  "    testthat (>= 3.0.0),",
  "    knitr,",
  "    rmarkdown",
  "VignetteBuilder: knitr",
  "Config/testthat/edition: 3"
)
writeLines(desc, file.path(pkg_path, "DESCRIPTION"))

# 3. Pro .Rbuildignore
ignore <- c(
  "^.*\\.Rproj$",
  "^\\.Rproj\\.user$",
  "^\\.github$",
  "^data-raw$",
  "^vignettes/.*\\.html$",
  "^vignettes/.*\\.R$"
)
writeLines(ignore, file.path(pkg_path, ".Rbuildignore"))

# 4. GitHub Actions (Continuous Integration)
ci_yaml <- c(
  "name: R-CMD-check",
  "on: [push, pull_request]",
  "jobs:",
  "  R-CMD-check:",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "      - uses: actions/checkout@v3",
  "      - uses: r-lib/actions/setup-r@v2",
  "      - uses: r-lib/actions/setup-r-dependencies@v2",
  "        with:",
  "          extra-packages: any::rcmdcheck",
  "      - name: Check",
  "        run: rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
)
writeLines(ci_yaml, file.path(pkg_path, ".github/workflows/check-standard.yaml"))

# 5. Example Vignette
vig_content <- c(
  "---",
  paste0("title: 'Getting Started with ", pkg_name, "'"),
  "output: rmarkdown::html_vignette",
  "vignette: >",
  "  %\\VignetteIndexEntry{Getting Started}",
  "  %\\VignetteEngine{knitr::rmarkdown}",
  "  %\\VignetteEncoding{UTF-8}",
  "---",
  "",
  "```{r, include = FALSE}",
  "knitr::opts_chunk$set(collapse = TRUE, comment = '#>')",
  "```",
  "",
  paste0("library(", pkg_name, ")"),
  "",
  "This is a professional vignette generated by Antigravity."
)
writeLines(vig_content, file.path(pkg_path, "vignettes", "getting-started.Rmd"))

cat(paste0("\n✅ Pro Package '", pkg_name, "' created with CI/CD and Vignettes!\n"))
